version: "3"

services:
  db:
    image: postgres:12.6
    restart: unless-stopped
    container_name: ilis_postgres
    env_file:
      - ./db.env
    networks:
      - ilis
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    container_name: ilis_redis
    networks:
      - ilis

  api:
    build: ./
    image: ilis_api
    restart: unless-stopped
    container_name: ilis_api
    env_file:
      - ./api.env
    networks:
      - ilis
    depends_on:
      - db
      - redis
    ports:
      - ${PORT}:5000

  worker:
    build: ./
    image: ilis_api
    restart: unless-stopped
    container_name: ilis_celery
    command: celery --app app.celery.celery worker
    env_file:
      - ./api.env
    networks:
      - ilis
    depends_on:
      - redis

  elastic:
    image: elasticsearch:7.10.1
    restart: unless-stopped
    container_name: ilis_elastic
    environment:
      - discovery.type=single-node
    networks:
      - ilis

networks:
  ilis:
    external: false
