"""Init database

Revision ID: bc2d523d136a
Revises:
Create Date: 2021-09-12 19:38:51.050733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = 'bc2d523d136a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('ilis_seq')))
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), server_default=sa.text("nextval('ilis_seq')"), nullable=False),
    sa.Column('login_id', sa.String(), nullable=False),
    sa.Column('login_type', sa.Enum('GOOGLE', 'VK', name='enumloginservice'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='enumuserrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('storages',
    sa.Column('storage_id', sa.Integer(), server_default=sa.text("nextval('ilis_seq')"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('storage_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), server_default=sa.text("nextval('ilis_seq')"), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=127), nullable=False),
    sa.Column('name_en', sa.String(length=127), nullable=False),
    sa.Column('desc_ru', sa.String(length=511), nullable=False),
    sa.Column('desc_en', sa.String(length=511), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.storage_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), server_default=sa.text("nextval('ilis_seq')"), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'BOOKED', 'CANCELED', 'COMPLETED', 'DELAYED', 'DENIED', 'LENT', name='enumrequeststatus'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('rent_starts_at', sa.DateTime(), nullable=False),
    sa.Column('rent_ends_at', sa.DateTime(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('items')
    op.drop_table('storages')
    op.drop_table('users')
    op.execute(DropSequence(Sequence('ilis_seq')))
    sa.Enum(name='enumloginservice').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='enumuserrole').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='enumrequeststatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
